version: "3.8"

services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src/proyecto_nombre:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./src/proyecto_nombre:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel_pg
    restart: always
    environment:
      POSTGRES_DB: nombre_de_la_base_de_datos
      POSTGRES_USER: dba_produccion
      POSTGRES_PASSWORD: contraceña_para_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
