services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src/sis_cronometro:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/sis_cronometro:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificado:/etc/nginx/certificado
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel_pg
    restart: always
    environment:
      POSTGRES_DB: carrera_db
      POSTGRES_USER: dba_produccion
      POSTGRES_PASSWORD: base1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
